name:                vscode-remote-try-haskell
version:             0.1.0.0
github:              "ueisele/vscode-remote-try-haskell"
license:             "Apache2"
author:              "Uwe Eisele"
maintainer:          "code@uweeisele.eu"
copyright:           "2022 Uwe Eisele"

extra-source-files:
- README.adoc

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ueisele/vscode-remote-try-haskell>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  vscode-remote-try-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vscode-remote-try-haskell

tests:
  vscode-remote-try-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vscode-remote-try-haskell
