name: Docker Image CI
on:
  push:
    paths:
    - ".devcontainer/Dockerfile"
    - ".github/**"
    branches:
    - main
  workflow_dispatch:

jobs:
  docker:
    strategy:
      fail-fast: false
      max-parallel: 0
      matrix:
        resolver: ["lts-18.21", "nightly-2022-01-15"]
        include:
        - resolver: lts-18.21
          ghc: 8.10.7
        - resolver: nightly-2022-01-15
          ghc: 9.0.2

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.docker-build-cache
        key: docker-build-cache-${{ github.sha }}
        restore-keys: |
          docker-build-cache

    - name: Build the Docker image
      run: |
        docker buildx build ./.devcontainer/ -f ./.devcontainer/Dockerfile \
          --build-arg GHC_VERSION=${{ matrix.ghc }} \
          --build-arg STACK_RESOLVER=${{ matrix.resolver }} \
          --tag ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}-$(git rev-parse --short "$GITHUB_SHA") \
          --cache-from type=local,src=/tmp/.docker-build-cache \
          --cache-to type=local,src=/tmp/.docker-build-cache-new

    - name: Move cache
      run: |
        rm -rf /tmp/.docker-build-cache
        mv /tmp/.docker-build-cache-new /tmp/.docker-build-cache

    - name: Push the Docker image
      run: |
        docker tag \
          ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}-$(git rev-parse --short "$GITHUB_SHA") \
          ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}
        docker tag \
          ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}-$(git rev-parse --short "$GITHUB_SHA") \
          ueisele/haskell-dev:${{ matrix.resolver }}
        docker push ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}-$(git rev-parse --short "$GITHUB_SHA")
        docker push ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}
        docker push ueisele/haskell-dev:${{ matrix.resolver }}
