name: Docker Image CI
on:
  push:
    paths:
    - ".devcontainer/Dockerfile"
    - ".github/**"
    branches:
    - main
  workflow_dispatch:

jobs:
  docker:
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        resolver: ["lts-18.21", "nightly-2022-01-15"]
        include:
        - resolver: lts-18.21
          ghc: 8.10.7
        - resolver: nightly-2022-01-15
          ghc: 9.0.2

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build ./.devcontainer/ -f ./.devcontainer/Dockerfile \
          --build-arg GHC_VERSION=${{ matrix.ghc }} \
          --build-arg STACK_RESOLVER=${{ matrix.resolver }} \
          --tag ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}-$(git rev-parse --short "$GITHUB_SHA")

    - name: Push the Docker image
      run: |
        docker tag \
          ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}-$(git rev-parse --short "$GITHUB_SHA") \
          ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}
        docker tag \
          ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}-$(git rev-parse --short "$GITHUB_SHA") \
          ueisele/haskell-dev:${{ matrix.resolver }}
        docker push ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}-$(git rev-parse --short "$GITHUB_SHA")
        docker push ueisele/haskell-dev:${{ matrix.resolver }}-${{ matrix.ghc }}
        docker push ueisele/haskell-dev:${{ matrix.resolver }}
